### ISSUE TITLE
Trying to install this manually, but no dice: "Failed to load plugin permalink-opener"

### ISSUE THREAD

**Issue by stanleyraywood** [kepano/obsidian-permalink-opener#1]
Steps: 
downloaded the folder, 
placed it in the .obsidian/plugins folder
refreshed the Obsidian vault, 
toggle the plugin
<img width="787" alt="image" src="https://github.com/kepano/obsidian-permalink-opener/assets/99240645/5f88f3ec-b59a-40ba-84d1-8712a7b434b4">
greeted by "Failed to load plugin permalink-opener"

All other plugins work, etc. I can't work out what's unique here, any ideas?

Thanks in advance.

**Comment by heyalmoo** [comment]
I have the same problem. Waiting to hear back.

**Comment by antomal** [comment]
I have the same problem

**Comment by kepano** [comment]
I am not able to reproduce this, but try 1.0.1

**Comment by antomal** [comment]
@kepano Thank you! At first this version did not start, but I read on the forum that you need to separately download file **main.js** and copy it to the directory with the plugin (hmm...). Instructions would be very useful (for people like me :-)

Very useful plugin! I'm currently creating my website on Obsidian + Hugo. Super!

Have a good day!

**Comment by kepano** [comment]
I'm adding it to the community directory so that won't be necessary.
